# Generated by Django 5.2 on 2025-04-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_rename_name_client_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
    ]
